from statistics import *
from app_lib.accidents_file_reader import *
from app_lib.main import *
from app_lib.class_calculations import  *



accident_data = AccidentsFileReader("car_accidents.xlsx")
accident_data = accident_data.print_all_cell_data()
calc = Calculations()

print("--------------------------------------------------------------------------------------------------------")
print("                                                 Car accidents in the UK ")
print("--------------------------------------------------------------------------------------------------------")
input()
print("The UK was amongst the bottom 25 countries for the number of casualities in car accidents  ")
input()
print("Though the UK was amongst the bottom 25, we were still beaten by countries like the Maldives, Norway,"
      " Malta, Sweden and 10 other countries ")
input()
print("I have obtained data from the British governments site for car accidents in 2017")
input()
print("Let us explore why car accidents happen in the UK")
input()

print("--------------------------------------------------------------------------------------------------------")
print("                                                 Descriptive Statistics ")
print("--------------------------------------------------------------------------------------------------------")
input()
calc.average_number_of_casualities(accident_data)
input()

print("--------------------------------------------------------------------------------------------------------")
print("                                                 User input ")
print("--------------------------------------------------------------------------------------------------------")
input()
a = input("What gender do we think is most likely to be in accident")
if a == "male":
    print(True)
elif a == "female":
    print(False)
input()
print("Lets see the casualty profile")

input()
print("--------------------------------------------------------------------------------------------------------")
print("                                                Casualty profile ")
print("--------------------------------------------------------------------------------------------------------")
input()
calc.average_age_of_casualities(accident_data)
input()
calc.sex_of_casuality(accident_data)
input()

print("--------------------------------------------------------------------------------------------------------")
print("                                                What causes car accidents? ")
print("--------------------------------------------------------------------------------------------------------")
input()
print("The hypothesis: Signs such as the stop signs are likely to have high number of accidents. Is this true?")
input()
calc.junction_control_with_high_casualities(accident_data)
input()
print("So the hypothesis is partially true, since only one sign had the highest number of accidents")
input()
print("Is it possible that the lighting conditions at the time of the accident was bad?")
input()
calc.lighting_condition(accident_data)
input()
print("Hmmmm, I would of thought give way signs were less visible during night time. "
      "However, it seems the lighting conditions were good")
input()
print("Could it possibly be the weather conditions that have made the Give way sign not efficient? ")
input()
calc.weather_with_high_casualities(accident_data)
input()
print("Yes, it seems that the weather has an influence on the efficency of how well Give way signs perform")
input()

print("--------------------------------------------------------------------------------------------------------")
print("                                                Conclusion ")
print("--------------------------------------------------------------------------------------------------------")
input()
print("From the analysis I have found that:")
print("- Car accidents are most likely to happen at junctions that have Give way signs")
input()
print("- Give way signs are less efficient when the weather is foggy")
input()
print("- Perhaps Give way signs need to be made brighter, or reconsidered in order to reduce accidents")
input()
print("The casualities are most likely to be men who are in their mid-30s ")

input()

print("--------------------------------------------------------------------------------------------------------")
print("                                                Retrospective  ")
print("--------------------------------------------------------------------------------------------------------")
input()
print(" I've learnt a lot from doing this project, which includes the following:")
input()
print("1- It is not very agile to write big block of codes")
input()
print("2- It's ok to dive in!")
input()
print("3- Use sudo code to help you know what you want to code ")
input()
print("4- Even when I struggled I had a lot of fun")

print("                                                Thank you for listening!  ")
